language: scala

# ignored, because if we do the ++ thing it uses the wrong
# scalaVersion to compile the sbt plugin which blows up
scala:
- 2.11.6
script:
- sbt test "readme/run --validate"
jdk:
- oraclejdk7
- oraclejdk8
sudo: false
